//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estate()
        {
            this.Comments = new HashSet<Comment>();
            this.EstateMedias = new HashSet<EstateMedia>();
        }
    
        public long Id { get; set; }
        public Nullable<int> Estates_TypeId { get; set; }
        public Nullable<long> AccountId { get; set; }
        public Nullable<long> TownId { get; set; }
        public Nullable<int> SaleOrRent { get; set; }
        public string EstateCode { get; set; }
        public string Area { get; set; }
        public Nullable<double> SalePrice { get; set; }
        public Nullable<long> SaleUnitId { get; set; }
        public Nullable<double> RentPrice { get; set; }
        public Nullable<long> RentUnitId { get; set; }
        public string HouseNumber { get; set; }
        public string LotCode { get; set; }
        public string Phone { get; set; }
        public string OwnerName { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string Note { get; set; }
        public Nullable<bool> IsHot { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<double> Long { get; set; }
        public string PinMainText { get; set; }
        public string Address { get; set; }
        public string LogBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual Estate_Types Estate_Types { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EstateMedia> EstateMedias { get; set; }
        public virtual SaleUnit SaleUnit { get; set; }
        public virtual RentUnit RentUnit { get; set; }
        public virtual Town Town { get; set; }
    }
}
