//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RealEstate.API.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EstateMedia
    {
        public long Id { get; set; }
        public Nullable<long> EstateId { get; set; }
        public string FileName { get; set; }
        public Nullable<long> FileSize { get; set; }
        public string ThumbnailUrl { get; set; }
        public string Url { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public string FriendlyFileName { get; set; }
    
        public virtual Estate Estate { get; set; }
    }
}
